### PR TITLE
Fix click command call

### LINKED ISSUE #94: Click fails in command
I was trying to use `rich-click` instead of `click` in [jpterm](https://github.com/davidbrochart/jpterm/pull/17), but it fails with:
```python
  File "/home/david/mambaforge/envs/jpterm/bin/jpterm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/david/github/davidbrochart/jpterm/jpterm/cli.py", line 16, in main
    command = click.command(_main)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/jpterm/lib/python3.11/site-packages/rich_click/__init__.py", line 53, in command
    return click_command(*args, cls=cls, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/jpterm/lib/python3.11/site-packages/click/decorators.py", line 190, in command
    assert cls is None, "Use 'command(cls=cls)(callable)' to specify a class."
AssertionError: Use 'command(cls=cls)(callable)' to specify a class.
```
I didn't investigate further, just posting to see if there is something obvious.

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #94.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks for this! Seems like quite a major change, do you know why / what's going on here? Will it break on older versions of click or anything?

**Comment by davidbrochart** [comment]
The change in Click was introduced in https://github.com/pallets/click/pull/2233, but I didn't investigate further. It seems to "just" be related to a type hint issue?

**Comment by davidbrochart** [comment]
I tested this change with Click v7.0 to v8.1.3, didn't find any issue.

**Comment by ewels** [comment]
Ok great, thanks! Just needs a changelog entry then and can merge.

**Review by ewels — APPROVED** [review]
Thanks!

**Comment by davidbrochart** [comment]
`rich-codex` seems to [fail](https://github.com/ewels/rich-click/actions/runs/3460592184/jobs/5777288920).

**Comment by ewels** [comment]
oof, I should probably have done a bit more testing before merge 👀

**Comment by ewels** [comment]
Ok, I should probably set up some CI to run this automatically, but if I go into the `examples` directory locally after this merge I get the following for the example scripts:

<details>

```
❯ for f in *py
do
echo $f; python $f > /dev/null; echo -e "\n";
done
01_simple.py


02_declarative.py


03_groups_sorting.py


04_rich_markup.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/04_rich_markup.py", line 7, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


05_markdown.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/05_markdown.py", line 7, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


06_arguments.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/06_arguments.py", line 9, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


07_custom_errors.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/07_custom_errors.py", line 9, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


08_metavars.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/08_metavars.py", line 7, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


08_metavars_default.py
Traceback (most recent call last):
  File "/Users/ewels/GitHub/ewels/rich-click/examples/08_metavars_default.py", line 4, in <module>
    @click.command()
  File "/Users/ewels/GitHub/ewels/rich-click/src/rich_click/__init__.py", line 53, in command
    return click_command(cls=cls)(*args, **kwargs)
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'


09_envvar.py


10_table_styles.py

```
</details>

So the following scripts fail:

- `04_rich_markup.py`
- `05_markdown.py`
- `06_arguments.py`
- `07_custom_errors.py`
- `08_metavars.py`
- `08_metavars_default.py`

**Comment by davidbrochart** [comment]
> oof, I should probably have done a bit more testing before merge

Me too, my bad.

**Comment by ewels** [comment]
ok, basic CI added in https://github.com/ewels/rich-click/pull/96

I'll revert this PR now and then we can try again 🤞🏻

**Comment by davidbrochart** [comment]
Another try in #98.
